site_name: SCARt.io
site_description: Application documentation
site_author: S3group

theme:
  name: mkdocs
  color_mode: auto
  custom_dir: themes/mkdocs/
  user_color_mode_toggle: true
  highlightjs: true
  locale: en
  navigation_depth: 3
  hljs_languages:
    - yaml
    - django

nav:
  - Home: index.md
  - Get started: getstarted.md
  - Basics:
    - Import: basic/import.md
    - Classification: basic/classification.md
    - Notice and Take Down: basic/ntd.md
    - Reporting: basic/report.md
  - Details:
    - Domain rules: details/rules.md
    - Abuse contacts: details/contacts.md
    - Classify questions: details/questions.md
    - Custom Webforms: details/custom_webforms.md
    - Email import whitelist: details/whitelist.md
    - ICCAM: details/iccam.md



